### PR TITLE
Fix Non-Differentiated Industry Specific FE Demand

### LINKED ISSUE #10: Non-Differentiated Industry Specific FE Demand
#2 destroyed the differentiation of industry subsector specific FE demand between scenarios, they all use SSP2 trajectories.

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
close #10

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
image
image
image
image
image

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Any idea what could have happened in `SSA` @JakobBD?
My initial guess/dread is that this is some kind of data availability hole, but I need to check.

**Comment by JakobBD** [comment]
What do you mean by "what could have happened"? 

The new results seem more plausible to me than the old ones. 

The huge specific FE demand in primary steel was not introduced by #2, but already by pik-piam/mrremind#507, I think. 
I attributed it to the more recent steel production data back then, but maybe it was a different issue that you now fixed?

This will solve some issues, especially SSA using H2-DRI in NPi to avoid exorbitant coal input.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
So a wonderful thing happened?!

**Review by JakobBD — APPROVED** [review]

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
@JakobBD Do you feel like investigating further, or are we just happy with the new `SSA` numbers?  Need any other plots to judge?  Test data is here: `/p/projects/rd3mod/inputdata/output_1.27/rev7.13-test-ind-specFE-fix_2b1450bc_remind.tgz`.

**Pull request merged**
