### PR TITLE
regionally differentiated convergence of feh2 share in fega

### PR DESCRIPTION
**Pull request by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q**
image

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
In case you want to tweak that in the future and look at it:
```R
library(tidyverse)
library(quitte)

f <- c('7.16' = '~/PIK/Remind_input/rev7.16_62eff8f7_remind',
       'test' = '~/PIK/Remind_input/rev7.16-regi_diff_feh2_shares_62eff8f7_remind')

d <- bind_rows(
  lapply(seq_along(f), function(i) {
    read_delim(file = file.path(f[[i]], 'f_fedemand.cs4r'),
               delim = ',',
               col_names = c('t', 'regi', 'scenario', 'pf', 'value'),
               col_types = 'icccd',
               comment = '*') %>% 
      filter(between(t, 2005, 2100),
             'gdp_SSP2' == scenario,
             grepl('fe(ga|h2)_', pf)) %>% 
      extract(pf, 'fety', '^(fe..)') %>% 
      group_by(t, regi, fety) %>% 
      summarise(value = sum(value),
                rev = names(f[i]),
                .groups = 'drop')
  })
) %>% 
  sum_total(regi, name = 'World') %>% 
  order.levels(fety = c('feh2', 'fega')) %>% 
  group_by(t, regi, rev) %>% 
  arrange(t, regi, rev, fety) %>% 
  mutate(value = cumsum(value)) %>% 
  ungroup() %>% 
  mutate(fety = ifelse('feh2' == fety, fety, 'fega + feh2'))

ggplot(d) +
  geom_line(aes(x = t, y = value, colour = fety, linetype = rev)) +
  facet_wrap(~ regi, scales = 'free_y') +
  labs(x = NULL, y = NULL, subtitle = 'SSP2') +
  theme_minimal() +
  theme(legend.position = 'inside',
        legend.position.inside = c(1, 0),
        legend.justification = c(1, 0),
        legend.direction = 'horizontal')
```

**Comment by robertpietzcker** [comment]
Thanks a lot!

one question: does the industry data processing happen always on EU21 level, so that the formulation 
```            region = c('CAZ', 'CHA', 'DEU', 'ECE', 'ECS', 'ENC', 'ESC', 'ESW', 'EWN', 'FRA', 'JPN', 'UKI', 'USA'),```
is sufficient so that the faster scaleup also happens for `EUR` in the H12 region version?

**Review by robertpietzcker — APPROVED** [review]
thanks!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> one question: does the industry data processing happen always on EU21 level, so that the formulation ` region = c('CAZ', 'CHA', 'DEU', 'ECE', 'ECS', 'ENC', 'ESC', 'ESW', 'EWN', 'FRA', 'JPN', 'UKI', 'USA'),` is sufficient so that the faster scaleup also happens for `EUR` in the H12 region version?

Technically, input data processing is done on country level.  But for the regressions and many parameters, we use `regionmapping_21_EU11`, as the highest-fidelity regional aggregation we care about.
So: parameters (21 regions) → FE demand (country level) → REMIND input (whatever is configured with `madrat`).

That will be a bit of work to adapt if/when we introduce more regions, but not complicated work.

**Pull request merged**
