### PR TITLE
Add files from mrremind

### PR DESCRIPTION
**Pull request by JakobBD**
FYI @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q @fbenke-pik

### CODE REVIEW

**Comment by JakobBD** [comment]
I decided against [filter-repo](https://github.com/newren/git-filter-repo/). This gives the industry package the whole history of mrremind, but I thought it may be worth it to keep the commit hashes the same, and so on.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Some unsolicited advice:
- I would wipe this whole repository.  There is no point in dragging these commits along
  ```
  * b98fbbe add dependency
  * 3d6c719 mark as madrat package
  * 5d248bb add initial setup
  * 31df625 Initial commit
  ```
- Start fresh with two `mrremind` branches (in different directories): `mrremind_wo_industry` and `mrindustry`.
- Make a list of .R files to move from one package to the other.
- For the `mrindustry` branch:
  - Delete all .R files not on the list (excluding `madrat.R`)
    ```
    $ ls R/*.R | grep -f <your-list-of-files> -Fv | xargs git rm
    $ git restore R/madrat.R
    ```
  - Delete all the other stuff (`man/`, `tests/`, `.Rbuildignore`, `.buildLibrary`, `.lintr`, `.pre-commit-config.yaml`)
  - Rename `mrremind` to `mrindustry`
    ```
    $ sed -i 's/mrremind/mrindustry/g' CITATION.cff DESCRIPTION README.md
    ```
  - Run `buildLibrary(updateType = 'none')`, sort out issues.
  - Reset the version number to 0 in `DESCRIPTION`.
  - Run `buildLibrary(updateType = 'development')`.
  - Install the package (locally).
 - For the `mrremind_wo_industry` branch:
  - Delete the files from the list.
    ```
    $ ls R/*.R | grep -f <your-list-of-files> -F | xargs git rm
    ````
  - Add `mrindustry` as a dependency.
  - Run `buildLibrary(updateType = 'none')`, sort out issues.
  - Run `buildLibrary(updateType = 'development')`
- Test both packages on the cluster.

**Comment by JakobBD** [comment]
Thanks for all that! That's pretty much what I did, except that I only took the R files from mrremind, and the rest from mrindustry, and merged the two. Of course I'm copy-pasting lines selectively from one repo to the other. I feel like I'm too far in to change strategies now. 

But apart from that, that's a really nice summary of steps and nice as an overview! The "sort out problems" bit seems so small and innocent :-D

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
image

**Pull request merged**
